### PR TITLE
Update Main.qml

### PR DESCRIPTION
**Pull request by gwado**
real correct links in menu
for podcasts link, deezer has changed its menu structure, the same link gives access to all podcasts except when we are in the favorites page where the same link displays our own podcast subscriptions.

### CODE REVIEW

**Comment by Tafitson** [comment]
Thank you for your contribution. Sadly your changes were based on the main branch, which was still on the xenial codebase. I just merged the focal branch on main, which of course led to conflicts in your PR. If you wouldn't mind to update the PR to resolve those conflicts, I'd be more than happy to test it and hopefully integrate your changes in a release soon.

**Comment by gwado** [comment]
I understand the idea of adding the theme change for faster access, but since it's accessible via the “profile” menu, removing it would lighten the “main app menu”.
Well, that's a detail.

I used your code for the theme toggle, but I had to add a timer for it to work properly. It's a bit of a DIY job.
But the whole Deezer app is DIY. Good DIY, eh! Because Deezer isn't very helpful in making its interface responsive (no less).
In any case, it seems to be working, and thanks for giving us your time to enjoy Deezer on Ubports!

EDIT : You'll have to test it out, though, as I don't quite understand the app's theme line (lomiri or not) and the app's name seems to pose a problem with its commentary.

**Review by gwado — COMMENTED** [review]
For Focal, the lines #14 et #15 can be : 
```
  theme.name: "Ubuntu.Components.Themes.SuruDark"  // Set the theme to SuruDark
  applicationName: "uteezer.tafitson"
```

**Comment by gwado** [comment]
And sorry for my misuse of comments, pull requests, commits, ... my use of git is solitary and very basic.

**Pull request merged**
